name: example
description: A new example.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  window_manager: ^0.3.7
  hash: ^1.0.4
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  #injectable: ^2.3.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  package_login_or_registration:
    path: ../
  flutter_secure_storage: ^9.0.0
  intl: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  #dart run build_runner build
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/Gradient.png
    - assets/img/Gradient_4x.png
    - assets/img/Gradient_75_93.png
  #fonts:
  #  - family: SF UI Display
flutter_intl:
  enabled: true
