name: money_tracker
description: Money Tracker.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

#dart --disable-analytics

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  #flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  #dart run flutter_native_splash:create
  flutter_native_splash: ^2.3.6
  intl: any
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  window_manager: ^0.3.7
  fl_chart: ^0.65.0
  hash: ^1.0.4
  get_it: ^7.6.4
  #injectable: ^2.3.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  internet_connection_checker: ^1.0.0+1
  uuid: ^4.2.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  flutter_colorpicker: ^1.0.3
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  #flutter clean
  #flutter pub cache repair
  #flutter pub run build_runner clean
  #Then run,
  #
  # flutter pub run build_runner build
  #
  #flutter clean && flutter pub cache repair && flutter pub run build_runner clean && flutter pub run build_runner build --delete-conflicting-outputs
  #
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  floor_generator: ^1.4.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  windows:
    generate: true
    image_path: assets/launcher/icon.png.ico
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/Gradient.png
    - assets/img/Gradient_4x.png
    - assets/img/Gradient_75_93.png
    - assets/launcher/icon.png
    - assets/launcher/icon.png.ico
  #fonts:
  #  - family: SF UI Display
flutter_intl:
  enabled: true
