name: money_tracker
description: Money Tracker.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  surf_lint_rules: ^3.0.0
  intl: any
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  window_manager: ^0.3.7
  fl_chart: ^0.64.0
  hash: ^1.0.4
  get_it: ^7.6.4
  #injectable: ^2.3.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.5
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  internet_connection_checker: ^1.0.0+1
  uuid: ^4.2.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  #flutter clean
  #flutter pub cache repair
  #flutter pub run build_runner clean
  #Then run,
  #
  # flutter pub run build_runner build
  #
  #flutter clean && flutter pub cache repair && flutter pub run build_runner clean && flutter pub run build_runner build --delete-conflicting-outputs
  #
  #flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs
  #dart run build_runner build --delete-conflicting-outputs
  #dart run build_runner build
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  floor_generator: ^1.4.2


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/Gradient.png
    - assets/img/Gradient_4x.png
    - assets/img/Gradient_75_93.png
  #fonts:
  #  - family: SF UI Display
flutter_intl:
  enabled: true
